# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: partiarelic/grpc/partiarelic.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "partiarelic.v1.ManualStartRequest" do
  end
  add_message "partiarelic.v1.ManualStartResponse" do
  end
end

module Partiarelic
  module V1
    ManualStartRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("partiarelic.v1.ManualStartRequest").msgclass
    ManualStartResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("partiarelic.v1.ManualStartResponse").msgclass
  end
end
