# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: partiarelic/grpc/partiarelic.proto for package 'partiarelic.v1'

require 'grpc'
require 'partiarelic/grpc/partiarelic_pb'

module Partiarelic
  module V1
    module App
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'partiarelic.v1.App'

        rpc :ManualStart, ManualStartRequest, ManualStartResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
